# vim:ft=kitty


font_size               9.5
font_family             MartianMono Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto

# Background color
background              #182728
cursor_text_color       #182728
inactive_tab_background #182728

# Foreground color
selection_foreground    #F9F5F4
foreground              #F9F5F4
inactive_tab_foreground #F9F5F4

# Primary color
selection_background    #CAD277
cursor                  #CAD277
url_color               #CAD277
active_tab_background   #CAD277

tab_bar_background      none
tab_bar_margin_color    none

active_border_color     #CAD277
inactive_border_color   #182728


# Black
color0                  #173626
color8                  #214c36

# Red
color1                  #903d3d
color9                  #ac4a4a

# Green
color2                  #5b903d
color10                 #6ead49

# Yellow
color3                  #908e3d
color11                 #acab4a

# Blue
color4                  #3d7b90
color12                 #4a94ac

# Pink
color5                  #813d90
color13                 #9a4aac

# Cyan
color6                  #3d9089
color14                 #4aaca4

# White 
color7                  #bfcbc5
color15                 #d6deda
