exec-once = udiskie &

exec-once = waybar &
exec-once = swaync -s ~/.config/swaync/style.css -c ~/.config/swaync/config.json &

exec-once = awww-daemon &
exec-once = awww img "$HOME/.config/bg.jpg" &

exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &

exec-once = hyprctl setcursor Bibata-Modern-Classic 22 &

exec-once = . ~/.config/scripts/home-folders.sh
