[mgr]
sort_by = "size"
ratio = [0, 4, 4]
sort_dir_first = true
linemode = "size"
show_symlink = true

[opener]
edit = [
  { run = 'code --wait "$@"', block = true },
]
open = [
  { run = 'mpv "$@"', block = true },
]

