input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

device {
    name = ducky-ducky-one2-mini-rgb-1
    kb_layout = ch
}

device {
    name = rapoo-rapoo-gaming-device
    sensitivity = -0.1
    accel_profile = flat
    
}
