$terminalFetch = fastfetch --config ~/.config/fastfetch/fastfetch.jsonc --logo ~/.config/fastfetch/logo.txt
#$terminalFetch =  echo " "

$terminal = kitty --hold $terminalFetch
$browser = brave
$fileManager = kitty yazi


$menuPath = ~/.config/rofi/menu.sh

$menu = . $menuPath

$screenshotMenu = . $menuPath -s
$appMenu = . $menuPath -a

$clipboardMenu = . $menuPath -c
$clipboardWipe = . $menuPath -w

$themeMenu = . $menuPath -t

$powerMenu = . $menuPath -p
