$terminal = kitty --hold fastfetch --config ~/.config/fastfetch/fastfetch.jsonc --logo ~/.config/fastfetch/logo.txt

$browser = brave
$fileManager = kitty yazi

$menu = . ~/.config/rofi/menu.sh -a
$fullMenu = . ~/.config/rofi/menu.sh -A

$controlMenu = . ~/.config/rofi/menu.sh
$powerMenu = . ~/.config/rofi/menu.sh -p

$clipboardMenu = . ~/.config/rofi/menu.sh -c
$clipboardWipe = cliphist wipe && . ~/.config/rofi/menu.sh -c

$screenshot = hyprshot -m region -o ~/Photos/Screenshots
$screenshotToClipboard = hyprshot -m region --clipboard-only

$colorpicker = hyprpicker -a | wl-copy
