$menuPath = ~/.config/scripts/menu.sh
$kittyScriptPath = ~/.config/scripts/kitty.sh


$terminal = . $kittyScriptPath --session session.conf
$terminalNormal = kitty
$browser = brave
$fileManager = . $kittyScriptPath --session yazi-session.conf yazi
$fileManagerNormal = $terminalNormal yazi 

$menu = . $menuPath
$appMenu = . $menuPath -a

$screenshotMenu = . $menuPath -s
$screenshotToClipboardMenu = . $menuPath -S

$clipboardMenu = . $menuPath -c
$clipboardWipe = . $menuPath -w

$themeMenu = . $menuPath -t

$powerMenu = . $menuPath -p
