source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/enviroment_variables.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/window_rules.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf

source = ~/.config/hypr/look_and_feel.conf
source = ~/.config/hypr/animations.conf

ecosystem {
	no_update_news = true
	no_donation_nag = true
}
