# vim:ft=kitty


# Theme: Galaxy

# Colors
# background: #221B56
# foreground: #E1FAFA
# primary:    #EF7DAE
# secondary:  #A586DB
# neutral:    #535996


# Background color
background                      #221B56
cursor_text_color               #221B56
cursor_text_color               #221B56
inactive_tab_background         #221B56

# Foreground color
selection_foreground            #E1FAFA
foreground                      #E1FAFA
inactive_tab_foreground         #E1FAFA

# Primary color
selection_background            #EF7DAE
cursor                          #EF7DAE
url_color                       #EF7DAE
active_tab_background           #EF7DAE

tab_bar_background              none
tab_bar_margin_color            none


# Black (neutral color)
color0                          #535996
color8                          #535996

# Red (primary color)
color1                          #EF7DAE
color9                          #EF7DAE

# Green (scondary color)
color2                          #A586DB
color10                         #A586DB

# Yellow (primary color)
color3                          #EF7DAE
color11                         #EF7DAE

# Blue (secondary color)
color4                          #A586DB
color12                         #A586DB

# Pink (primary color)
color5                          #EF7DAE
color13                         #EF7DAE

# Cyan (secondary color)
color6                          #A586DB
color14                         #A586DB

# White (foreground color)
color7                          #E1FAFA
color15                         #E1FAFA
