#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

#PS1='[\u@\h \W]\$ '
#PS1='\[\e[0;97m\](\@)->\[\e[0;35m\][\u]\[\e[0;32m\](\W)\[\e[0;33m\]$\[\e[0;97m\] '
PS1='\[\e[0;97m\](\@)->\[\e[0;32m\](\w)\[\e[0;97m\]\n > '

export EDITOR="micro"
export VISUAL="micro"
export SUDO_EDITOR="micro"

alias vsc='code'
alias mic='micro'

alias a='alias'

alias nxre-laptop='sudo nixos-rebuild switch --flake /etc/nixos#laptop --impure && hyprctl reload'
alias nxre-desktop='sudo nixos-rebuild switch --flake /etc/nixos#desktop --impure && hyprctl reload'

alias nxup-laptop='sudo nixos-rebuild switch --flake /etc/nixos#laptop --impure --update-input nixpkgs'
alias nxup-desktop='sudo nixos-rebuild switch --flake /etc/nixos#desktop --impure --update-input nixpkgs'

alias nxls-gens='sudo nixos-rebuild list-generations'
alias nxrm-gens='sudo nix-collect-garbage -d'

alias s='sudo'
alias si='sudo -i'
alias se='sudoedit'
alias st='sudo touch'
alias sm='sudo mkdir'

alias c='clear'
alias ca='clear &&'

alias cm='cmatrix'
alias pk='pkill'
