#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

#PS1='[\u@\h \W]\$ '
#PS1='\[\e[0;97m\](\@)->\[\e[0;35m\][\u]\[\e[0;32m\](\W)\[\e[0;33m\]$\[\e[0;97m\] '
PS1='\[\e[0;97m\](\@)->\[\e[0;32m\](\W)\[\e[0;97m\]\n > '

export EDITOR=nvim
export VISUAL=nvim
export SUDO_EDITOR=nvim

alias a='alias'

alias nxre-laptop='sudo nixos-rebuild switch --flake /etc/nixos#laptop'
alias nxre-desktop='sudo nixos-rebuild switch --flake /etc/nixos#desktop' 
alias nxls-gens='sudo nixos-rebuild list-generations'
alias nxrm-gens='sudo nix-collect-garbage -d'

alias hlre='hyprctl reload'

alias se='sudoedit'
alias si='sudo -i'
alias st='sudo touch'
alias sm='sudo mkdir'

alias nv='nvim'
alias ynv='nvim $(yazi)'
alias yse='sudoedit $(yazi)'
alias ymp='mpv $(yazi)'

alias c='clear'
alias ca='clear &&'

alias cm='cmatrix'
alias pk='pkill'
