$menuPath = ~/.config/scripts/menu.sh
$kittyScriptPath = ~/.config/scripts/kitty.sh


$terminal = bash $kittyScriptPath
$terminalNormal = kitty
$browser = brave
$fileManager = bash $kittyScriptPath yazi
$fileManagerNormal = $terminalNormal yazi 

$menu = bash $menuPath
$appMenu = bash $menuPath -a

$screenshotMenu = bash $menuPath -s

$clipboardMenu = bash $menuPath -c
$clipboardWipe = bash $menuPath -w

$themeMenu = bash $menuPath -t

$powerMenu = bash $menuPath -p
