misc {
	disable_splash_rendering = false
}

# Restart after editing permissions
ecosystem {
	enforce_permissions = true
	no_donation_nag = true
}

permission = /nix/store/[a-z0-9]{32}-grim-[0-9.]*/bin/grim, screencopy, allow
permission = /nix/store/[a-z0-9]{32}-obs-studio-[0-9.]*/bin/obs-studio, screencopy, allow
