$terminal = kitty --hold fastfetch --config ~/.config/fastfetch/fastfetch.jsonc --logo ~/.config/fastfetch/logo.txt

$browser = brave
$fileManager = kitty yazi

$appMenu = . ~/.config/rofi/menu.sh -a

$screenshotMenu = . ~/.config/rofi/menu.sh
$powerMenu = . ~/.config/rofi/menu.sh -p

$clipboardMenu = . ~/.config/rofi/menu.sh -c
$clipboardWipe = . ~/.config/rofi/menu.sh -w
