windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
   
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

general {
    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
    vrr = 0
}

xwayland {
    force_zero_scaling = true
}


