windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = opacity 0.9 0.6, class:^(kitty)$

windowrule = center, title:^(wiremix)$

general {
    gaps_in = 6
    gaps_out = 12

    border_size = 3

    col.active_border = rgba(AD5295FF) rgba(3E3996FF) 45deg
    col.inactive_border = rgba(1586DFFF) rgba(BEECF0FF)

    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 5
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 3
	    noise = 0.03
        vibrancy = 0.1696
    }
}

layerrule = blur, rofi
layerrule = ignorezero, rofi

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
    vrr = 0
}

xwayland {
    force_zero_scaling = true
}
