source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/enviroment_variables.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/look_and_feel.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf

bind = $main, B, exec, pkill waybar
bind = $main, N, exec, waybar
