animations {
    enabled = yes

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = cubicBezier,    0.6,  -0.28,0.7,  0.045

    #           NAME,             ONOFF, SPEED, CURVE,          STYLE
    animation = global,           1,     10   , default
    animation = border,           1,     3.39 , easeInOutCubic
    animation = borderangle,      1,     18   , almostLinear
    animation = windows,          1,     4.79 , easeOutQuint
    animation = windowsIn,        1,     1.9  , almostLinear  , gnomed
    animation = windowsOut,       1,     2.49 , cubicBezier   , popin
    animation = fadeIn,           1,     2    , almostLinear
    animation = fadeOut,          1,     3    , almostLinear
    animation = fade,             1,     3    , quick
    animation = layers,           1,     3.8  , easeOutQuint
    animation = layersIn,         1,     4    , easeOutQuint  , fade
    animation = layersOut,        1,     1.5  , linear        , fade
    animation = fadeLayersIn,     1,     1.79 , almostLinear
    animation = fadeLayersOut,    1,     1.39 , almostLinear
    animation = workspaces,       1,     1.94 , cubicBezier
    animation = workspacesIn,     1,     2.6  , linear        , slidefadevert 2%
    animation = workspacesOut,    1,     1.8  , almostLinear  , fade
    animation = zoomFactor,       1,     1    , quick
    animation = specialWorkspace, 1,     2.8  , linear        , slidefadevert 2%
}
