# vim:fileencoding=utf-8:foldmethod=marker

include current-theme.conf

shell zsh

confirm_os_window_close 0
allow_remote_control yes

detect_urls yes

window_padding_width 4 4 4 4

font_size 9.5
font_family      family="MartianMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.05 0.3
cursor_blink_interval 0.5

map super+shift+h previous_tab
map super+shift+j new_tab
map super+shift+k close_tab
map super+shift+l next_tab

map super+shift+y move_tab_backward
map super+shift+o move_tab_forward
map super+shift+u set_tab_title

tab_title_template {index}

